name: Build and Deploy to VPS

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'  # Specify the Go version you're using
    
    - name: Build
      run: go build -o main .
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        scp ./main $USER@$HOST:/go-web/main
        ssh $USER@$HOST "sudo systemctl restart goweb"
