name: Deploy Go Web App

on:
  push:
    branches: [ main ]  # Trigger the action on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Latest stable version as of April 2024

    - name: Build
      run: go build -o main  # Build your Go application

    - name: Deploy to VPS
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no main $USER@$HOST:/home/$USER/main_new
        ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST '
          sudo service goweb stop &&
          sudo mv /home/$USER/main_new /go-web/main &&
          sudo chown root:root /go-web/main &&
          sudo chmod 755 /go-web/main &&
          sudo service goweb start &&
          echo "Deployment completed at $(date)" | sudo tee -a /logs/deployment.log &&
          echo "Service status:" | sudo tee -a /logs/deployment.log &&
          sudo service goweb status | sudo tee -a /logs/deployment.log &&
          echo "----------------------------------------" | sudo tee -a /logs/deployment.log
        '
        rm -f private_key
