name: Deploy Go Web App

on:
  push:
    branches: [ main ]  # Trigger the action on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Specify the Go version you're using

    - name: Build
      run: go build -o main  # Build your Go application

    - name: Deploy to VPS
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no main $USER@$HOST:/go-web/
        ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST '
          sudo systemctl stop goweb &&
          sudo rm -rf /go-web/* &&
          sudo mv /go-web/main /go-web/ &&
          sudo systemctl start goweb
        '
        rm -f private_key
